CREATE TABLE IF NOT EXISTS WAREHOUSE(
    ID VARCHAR(36) NOT NULL PRIMARY KEY,
    NAME VARCHAR(200) NOT NULL
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS CAR(
    ID VARCHAR(36) NOT NULL PRIMARY KEY,
    WAREHOUSE_ID VARCHAR(36) NOT NULL,
    BRAND VARCHAR(100) NOT NULL,
    NAME VARCHAR(200) NOT NULL
)ENGINE=InnoDB;