#!/bin/bash

echo "List people"
curl --location 'http://localhost:8080/v1/people' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json'
echo "\n"

echo "Creating person"
curl --location 'http://localhost:8080/v1/people' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json' \
--data '{
    "firstName": "Mary",
    "lastName": "Smith"
}'
echo "\n"

echo "List people"
curl --location 'http://localhost:8080/v1/people' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json'
echo "\n"

echo "Get Person from Id 2"
curl --location 'http://localhost:8080/v1/people/2' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json'
echo "\n"

echo "Get Person from UUID"
curl --location 'http://localhost:8080/v1/people/uuid/60b15f8f-0f9c-4242-b9d7-6dfa1d98f633' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json'
echo "\n"

echo "Update person from Id 2"
curl --location --request PUT 'http://localhost:8080/v1/people/2' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json' \
--data '{
    "uuid": "959af7a1-9e20-4a65-a681-e3163cc34666",
    "firstName": "Joao",
    "lastName": "Silva"
}'
echo "\n"

echo "List people"
curl --location 'http://localhost:8080/v1/people' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json'
echo "\n"

echo "Delete person from id 2"
curl --location --request DELETE 'http://localhost:8080/v1/people/2' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json'
echo "\n"

echo "List people"
curl --location 'http://localhost:8080/v1/people' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json'
echo "\n"


