services:

  neo4j:
    image: neo4j:5.28
    container_name: neo4j
    restart: unless-stopped
    environment:
      NEO4J_AUTH: neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j-data:/data

volumes:
  neo4j-data: