version: '1'

services:
  postgres:
    image: postgres:latest
    container_name: java_stress_test_poc
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: test
      POSTGRES_DB: java_stress_test_poc
    ports:
      - "5432:5432"
    volumes:
      - java_stress_test_poc_postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - java-stress-test-poc

volumes:
  java_stress_test_poc_postgres_data:

networks:
  java-stress-test-poc:
    driver: bridge