version: '1'

services:
  postgres:
    image: postgres:latest
    container_name: java_stress_test_poc
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: test
      POSTGRES_DB: java_stress_test_poc
    ports:
      - "5432:5432"
    volumes:
      - java_stress_test_poc_postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      java-stress-test-poc:
        ipv4_address: 10.5.0.2

  dungeon-service:
    container_name: dungeon-service
    depends_on:
      - postgres
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      POSTGRES_URL: postgres
    networks:
      java-stress-test-poc:
        ipv4_address: 10.5.0.3

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=gatling
      - INFLUXDB_USER=gatling
      - INFLUXDB_USER_PASSWORD=gatling
    volumes:
      - java_stress_test_poc_influxdb-data:/var/lib/influxdb
    networks:
      java-stress-test-poc:
        ipv4_address: 10.5.0.4

  influxdb-exporter:
    image: prom/influxdb-exporter
    container_name: influxdb-exporter
    ports:
      - "9122:9122"
    command:
      - "--influxdb-url=http://influxdb:8086"
      - "--influxdb.database=gatling"
    networks:
      java-stress-test-poc:
        ipv4_address: 10.5.0.5

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./infra/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      java-stress-test-poc:
        ipv4_address: 10.5.0.6

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - java_stress_test_poc_grafana_data:/var/lib/grafana
    networks:
      java-stress-test-poc:
        ipv4_address: 10.5.0.7

volumes:
  java_stress_test_poc_postgres_data:
  java_stress_test_poc_influxdb-data:
  java_stress_test_poc_grafana_data:

networks:
  java-stress-test-poc:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
